services:
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar-scanner
    platform: linux/amd64
    volumes:
      - /path/to/your/project:/usr/src
    working_dir: /usr/src
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_LOGIN=<YOUR_SONAR_TOKEN>
    networks:
      - sonar-network
    entrypoint: ["sonar-scanner"]

networks:
  sonar-network:
    external: true
